import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '../supabaseClient';
import ChatMessage from '../components/ChatMessage';
import { Loader2, AlertCircle } from 'lucide-react';

const SharedChatPage = () => {
    const { shareId } = useParams();
    const [conversation, setConversation] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchConversation = async () => {
            try {
                const { data, error } = await supabase
                    .from('conversations')
                    .select('*')
                    .eq('id', shareId)
                    .single();

                if (error) throw error;
                setConversation(data);
            } catch (err) {
                console.error('Error fetching shared chat:', err);
                setError('Chat not found or access denied.');
            } finally {
                setLoading(false);
            }
        };

        if (shareId) {
            fetchConversation();
        }
    }, [shareId]);

    if (loading) {
        return (
            <div className="h-screen w-screen flex flex-col items-center justify-center bg-[#212121] text-emerald-500 gap-4">
                <Loader2 className="h-8 w-8 animate-spin" />
                <p className="text-gray-400">Loading Shared Conversation...</p>
            </div>
        );
    }

    if (error || !conversation) {
        return (
            <div className="h-screen w-screen flex flex-col items-center justify-center bg-[#212121] text-red-400 gap-4">
                <AlertCircle className="h-10 w-10" />
                <p className="text-xl font-semibold">{error || 'Conversation Not Found'}</p>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[#212121] text-white flex flex-col">
            {/* Header */}
            <header className="flex items-center justify-between px-6 py-4 border-b border-[#2f2f2f] bg-[#1a1a1a] sticky top-0 z-50">
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-emerald-500/10 rounded-lg">
                        <img src="/icons/logo-hdi.png" alt="Logo" className="w-8 h-8" />
                    </div>
                    <div>
                        <h1 className="font-semibold text-lg">{conversation.title || 'Shared Chat'}</h1>
                        <p className="text-xs text-gray-400">Shared via ChatHDI</p>
                    </div>
                </div>
            </header>

            {/* Messages */}
            <main className="flex-1 max-w-4xl w-full mx-auto p-4 md:p-6 overflow-y-auto">
                <div className="space-y-6 pb-20">
                    {conversation.messages.map((message, index) => (
                        <ChatMessage
                            key={index}
                            message={message}
                            isTyping={false}
                            readOnly={true} // Add a readOnly prop to ChatMessage if needed, or just partial props
                            // Pass dummy handlers to prevent errors if ChatMessage expects them
                            onCopy={() => navigator.clipboard.writeText(message.content)}
                        />
                    ))}
                </div>
            </main>

            {/* Footer */}
            <footer className="text-center py-6 text-gray-500 text-sm border-t border-[#2f2f2f] bg-[#1a1a1a]">
                <p>Generated by ChatHDI AI Assistant</p>
            </footer>
        </div>
    );
};

export default SharedChatPage;
