import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Header, ImageRun } from 'docx';

// Helper to convert image URL to base64
const getLogoBase64 = async () => {
    try {
        const response = await fetch('/logo-hdi.png');
        const blob = await response.blob();
        return new Promise((resolve) => {
            const reader = new FileReader();
            reader.onloadend = () => {
                // Return just the base64 data without the data URL prefix
                const base64 = reader.result.split(',')[1];
                resolve(base64);
            };
            reader.readAsDataURL(blob);
        });
    } catch (error) {
        console.error('Failed to load logo:', error);
        return null;
    }
};

/**
 * Generates a Word document from chat content
 * @param {string} content - The text content to convert
 * @param {string} title - Document title
 * @returns {Promise<Blob>} - Word document as Blob
 */
export const generateWordFromText = async (content, title = "ChatHDI Export") => {
    const logoBase64 = await getLogoBase64();

    // Parse content into paragraphs
    const lines = content.split('\n');
    const children = [];

    // Title
    children.push(
        new Paragraph({
            text: title,
            heading: HeadingLevel.TITLE,
            spacing: { after: 400 },
            alignment: AlignmentType.CENTER
        })
    );

    // Subtitle with date
    children.push(
        new Paragraph({
            children: [
                new TextRun({
                    text: `Generated by ChatHDI - ${new Date().toLocaleDateString('id-ID', { year: 'numeric', month: 'long', day: 'numeric' })}`,
                    italics: true,
                    color: "666666"
                })
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 }
        })
    );

    // Separator
    children.push(
        new Paragraph({
            border: {
                bottom: { color: "00BFA5", size: 12, style: BorderStyle.SINGLE }
            },
            spacing: { after: 400 }
        })
    );

    // Process content lines
    lines.forEach(line => {
        const trimmed = line.trim();
        if (!trimmed) {
            children.push(new Paragraph({ text: "" }));
            return;
        }

        // Detect headers
        if (trimmed.startsWith('# ')) {
            children.push(new Paragraph({
                text: trimmed.substring(2),
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }));
        } else if (trimmed.startsWith('## ')) {
            children.push(new Paragraph({
                text: trimmed.substring(3),
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 150 }
            }));
        } else if (trimmed.startsWith('### ')) {
            children.push(new Paragraph({
                text: trimmed.substring(4),
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 200, after: 100 }
            }));
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
            // Bullet points
            children.push(new Paragraph({
                text: trimmed.substring(2),
                bullet: { level: 0 },
                spacing: { before: 100, after: 100 }
            }));
        } else if (/^\d+\.\s/.test(trimmed)) {
            // Numbered list
            const text = trimmed.replace(/^\d+\.\s/, '');
            children.push(new Paragraph({
                text: text,
                numbering: { reference: "default-numbering", level: 0 },
                spacing: { before: 100, after: 100 }
            }));
        } else if (trimmed.startsWith('```')) {
            // Code block - skip the language marker
            return;
        } else if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
            // Bold text
            children.push(new Paragraph({
                children: [
                    new TextRun({
                        text: trimmed.slice(2, -2),
                        bold: true
                    })
                ],
                spacing: { before: 100, after: 100 }
            }));
        } else {
            // Regular paragraph
            children.push(new Paragraph({
                text: trimmed,
                spacing: { before: 100, after: 100 }
            }));
        }
    });

    // Create document
    const docConfig = {
        title: title,
        description: "Generated by ChatHDI AI",
        sections: [{
            properties: {},
            children: children
        }],
        numbering: {
            config: [{
                reference: "default-numbering",
                levels: [{
                    level: 0,
                    format: "decimal",
                    text: "%1.",
                    alignment: AlignmentType.LEFT
                }]
            }]
        }
    };

    // Add header with logo if available
    if (logoBase64) {
        try {
            docConfig.sections[0].headers = {
                default: new Header({
                    children: [
                        new Paragraph({
                            children: [
                                new ImageRun({
                                    data: Buffer.from(logoBase64, 'base64'),
                                    transformation: { width: 50, height: 50 }
                                }),
                                new TextRun({
                                    text: "  ChatHDI AI",
                                    bold: true,
                                    color: "00BFA5"
                                })
                            ],
                            alignment: AlignmentType.LEFT
                        })
                    ]
                })
            };
        } catch (e) {
            console.warn('Could not add logo to header:', e);
        }
    }

    const doc = new Document(docConfig);

    // Generate blob
    const blob = await Packer.toBlob(doc);
    return blob;
};

/**
 * Download Word document
 * @param {string} content - The text content
 * @param {string} title - Document title
 * @param {string} filename - Output filename
 */
export const downloadWord = async (content, title, filename = "ChatHDI_Export.docx") => {
    const blob = await generateWordFromText(content, title);

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
