-- ChatHDI RAG v2: 384-dimensional embeddings generated by embeddinggemma.
-- The legacy embedding column is preserved so existing content is not deleted.

create extension if not exists vector with schema extensions;

alter table public.document_sections
  add column if not exists chunk_index integer,
  add column if not exists embedding_model text,
  add column if not exists embedding_v2 extensions.vector(384);

create index if not exists document_sections_embedding_v2_hnsw
  on public.document_sections
  using hnsw (embedding_v2 vector_cosine_ops)
  where embedding_v2 is not null;

alter table public.documents enable row level security;
alter table public.document_sections enable row level security;

drop policy if exists "rag_documents_select" on public.documents;
create policy "rag_documents_select"
  on public.documents for select
  to authenticated
  using (is_shared = true or user_id = auth.uid());

drop policy if exists "rag_sections_select" on public.document_sections;
create policy "rag_sections_select"
  on public.document_sections for select
  to authenticated
  using (
    exists (
      select 1
      from public.documents document
      where document.id = document_sections.document_id
        and (document.is_shared = true or document.user_id = auth.uid())
    )
  );

drop policy if exists "rag_sections_insert" on public.document_sections;
create policy "rag_sections_insert"
  on public.document_sections for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.documents document
      where document.id = document_sections.document_id
        and document.user_id = auth.uid()
    )
  );

drop policy if exists "rag_sections_update" on public.document_sections;
create policy "rag_sections_update"
  on public.document_sections for update
  to authenticated
  using (
    exists (
      select 1
      from public.documents document
      where document.id = document_sections.document_id
        and document.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.documents document
      where document.id = document_sections.document_id
        and document.user_id = auth.uid()
    )
  );

drop function if exists public.match_document_sections_v2(extensions.vector, double precision, integer);
drop function if exists public.match_document_sections_v2(extensions.vector, double precision, integer, text);
create or replace function public.match_document_sections_v2(
  query_embedding extensions.vector(384),
  match_threshold double precision default 0.45,
  match_count integer default 5,
  query_text text default ''
)
returns table (
  document_name text,
  content text,
  similarity double precision,
  is_shared boolean
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    document.name as document_name,
    section.content,
    (
      (1 - (section.embedding_v2 <=> query_embedding)) * 0.85
      + case
          when query_text = '' then 0
          else least(
            ts_rank_cd(
              to_tsvector('simple', section.content),
              plainto_tsquery('simple', query_text)
            ),
            1
          ) * 0.15
        end
    )::double precision as similarity,
    document.is_shared
  from public.document_sections section
  join public.documents document on document.id = section.document_id
  where section.embedding_v2 is not null
    and (document.is_shared = true or document.user_id = auth.uid())
    and 1 - (section.embedding_v2 <=> query_embedding) >= match_threshold
  order by similarity desc
  limit least(greatest(match_count, 1), 20);
$$;

grant execute on function public.match_document_sections_v2(
  extensions.vector,
  double precision,
  integer,
  text
) to authenticated;
